In [23]:
import numpy as np

In [41]:
# Creating Arrays..............

a = [[1,2,3,4], [5,6,7,8]]


arr = np.array(a)


arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# dir(arr)

# list(range(0, 10, 2))

arr = np.arange(0,11,2)

arr

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.zeros((2,4), dtype = "int")


# Dimension = row X column

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
np.ones((3,3), dtype = "int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
np.full((2,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [54]:
# [1, 0, 0]
# [0, 1, 0]
# [0, 0, 1]


np.eye(5, dtype = "int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [55]:
np.diag([6,7,8,9])

array([[6, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [59]:
np.random.randint(0,10,6)

array([0, 9, 5, 6, 0, 7])

In [62]:
np.random.randint(0,10,(2,4))

array([[5, 8, 4, 9],
       [6, 3, 5, 9]])

In [68]:
arr = np.random.randint(0,10,(2,4))

arr

array([[5, 0, 2, 3],
       [7, 4, 5, 2]])

In [69]:
arr.min()

0

In [70]:
arr.max()

7

In [72]:
arr.argmax()

4

In [71]:
arr.argmin()

1

In [82]:
arr.reshape(-1,1)

array([[5],
       [0],
       [2],
       [3],
       [7],
       [4],
       [5],
       [2]])

In [84]:
np.array([6,4,24,1,-9,8]).reshape(2,-1)

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [85]:
np.array([[6,  4, 24], [1, -9,  8]])

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [87]:
x = np.array([1,2,3,4,5,6]).reshape(2,-1)


y = np.array([7,8,9,10,11,12]).reshape(2,-1)

print(x)

print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [88]:
np.add(x,y)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [92]:
np.subtract(y,x)

array([[6, 6, 6],
       [6, 6, 6]])

In [95]:
np.divide(y,x)

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [96]:
np.multiply(x, y)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [97]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.sqrt(y)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [100]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [101]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:

# Row wise sum


np.sum(x,axis = 1)

array([ 6, 15])

In [104]:
# Column wise sum

np.sum(x,axis = 0)

array([5, 7, 9])

In [107]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# row X column

# x = a   X  b

# x.T = b  X  a 


x.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [109]:
mat = np.array([4,0,1,-9]).reshape(2,-1)

print(mat)

print('\n -------- Scaler Multiplication --------- \n')

print(mat * 2)



[[ 4  0]
 [ 1 -9]]

 -------- Scaler Multiplication --------- 

[[  8   0]
 [  2 -18]]


In [110]:
x = np.arange(1,7).reshape(2,-1)

y = np.arange(7,13).reshape(-1,2)

print(x)

print('\n -------- Matrix --------- \n')

print(y)

[[1 2 3]
 [4 5 6]]

 -------- Matrix --------- 

[[ 7  8]
 [ 9 10]
 [11 12]]


In [111]:
# [ 2  X  3 ]    .    [ 3  X  2 ]   =  [ 2  X  2 ]


np.dot(x,y)



array([[ 58,  64],
       [139, 154]])

In [ ]:


[1   X   3]  .  [3   X  4]

[1   X   4]
